In [2]:
import xlrd

book = xlrd.open_workbook("data/SOWC-2016_all-tables_261.xlsx")
sheet = book.sheet_by_name("Table 9")
data = {}

for i in range(7, sheet.nrows):
    row = sheet.row_values(i)
    country = row[1]
    data[country] = {
        'child_labor': {
            'total': [row[2], row[3]],
            'male': [row[4], row[5]],
            'female': [row[6], row[7]]
        },
        'child_marriage': {
            'married_by_15': [row[8], row[9]],
            'married_by_18': [row[10], row[11]]
        }
    }
    if country == "Zimbabwe":
        break

import pprint
pprint.pprint(data)

{'Afghanistan': {'child_labor': {'female': [24.2, 'y'],
                                 'male': [34.1, 'y'],
                                 'total': [29.4, 'y']},
                 'child_marriage': {'married_by_15': ['–', ''],
                                    'married_by_18': [32.8, '']}},
 'Albania': {'child_labor': {'female': [3.9, 'y'],
                             'male': [6.2, 'y'],
                             'total': [5.1, 'y']},
             'child_marriage': {'married_by_15': [0.2, ''],
                                'married_by_18': [9.6, '']}},
 'Algeria': {'child_labor': {'female': [4.5, ''],
                             'male': [5.5, ''],
                             'total': [5.0, '']},
             'child_marriage': {'married_by_15': [0.4, ''],
                                'married_by_18': [2.5, '']}},
 'Andorra': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Angola': {'child_labor': {'female': [24.8, 'x'],
                            'male': [22.1, 'x'],
                            'total': [23.5, 'x']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Antigua and Barbuda': {'child_labor': {'female': ['–', '  '],
                                         'male': ['–', ' '],
                                         'total': ['–', ' ']},
                         'child_marriage': {'married_by_15': ['–', ''],
                                            'married_by_18': ['–', '']}},
 'Argentina': {'child_labor': {'female': [3.9, ''],
                               'male': [4.8, ''],
                               'total': [4.4, '']},
               'child_marriage': {'married_by_15': ['–', ''],
                                  'married_by_18': ['–', '']}},
 'Armenia': {'child_labor': {'female': [2.9, ''],
                             'male': [4.7, ''],
                             'total': [3.9, '']},
             'child_marriage': {'married_by_15': [0.0, ''],
                                'married_by_18': [7.2, '']}},
 'Australia': {'child_labor': {'female': ['–', '  '],
                               'male': ['–', ' '],
                               'total': ['–', ' ']},
               'child_marriage': {'married_by_15': ['–', ''],
                                  'married_by_18': ['–', '']}},
 'Austria': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Azerbaijan': {'child_labor': {'female': [5.4, 'x,y'],
                                'male': [7.5, 'x,y'],
                                'total': [6.5, 'x,y']},
                'child_marriage': {'married_by_15': [1.9, ''],
                                   'married_by_18': [11.0, '']}},
 'Bahamas': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Bahrain': {'child_labor': {'female': [3.0, 'x'],
                             'male': [6.3, 'x'],
                             'total': [4.6, 'x']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Bangladesh': {'child_labor': {'female': [3.9, 'y'],
                                'male': [4.6, 'y'],
                                'total': [4.3, 'y']},
                'child_marriage': {'married_by_15': [18.1, ''],
                                   'married_by_18': [52.3, '']}},
 'Barbados': {'child_labor': {'female': [1.4, '  '],
                              'male': [2.5, ' '],
                              'total': [1.9, ' ']},
              'child_marriage': {'married_by_15': [0.7, ''],
                                 'married_by_18': [10.7, '']}},
 'Belarus': {'child_labor': {'female': [1.5, '  '],
                             'male': [1.3, '  '],
                             'total': [1.4, '  ']},
             'child_marriage': {'married_by_15': [0.0, ''],
                                'married_by_18': [3.2, '']}},
 'Belgium': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Belize': {'child_labor': {'female': [1.2, 'y'],
                            'male': [5.1, 'y'],
                            'total': [3.2, 'y']},
            'child_marriage': {'married_by_15': [3.4, ''],
                               'married_by_18': [25.9, '']}},
 'Benin': {'child_labor': {'female': [15.6, '  '],
                           'male': [14.9, '  '],
                           'total': [15.3, '  ']},
           'child_marriage': {'married_by_15': [10.5, ''],
                              'married_by_18': [31.9, '']}},
 'Bhutan': {'child_labor': {'female': [3.1, ''],
                            'male': [2.6, ''],
                            'total': [2.9, '']},
            'child_marriage': {'married_by_15': [6.2, ''],
                               'married_by_18': [25.8, '']}},
 'Bolivia (Plurinational State of)': {'child_labor': {'female': [24.4, 'x,y'],
                                                      'male': [28.2, 'x,y'],
                                                      'total': [26.4, 'x,y']},
                                      'child_marriage': {'married_by_15': [3.2,
                                                                           ''],
                                                         'married_by_18': [21.7,
                                                                           '']}},
 'Bosnia and Herzegovina': {'child_labor': {'female': [3.9, 'x'],
                                            'male': [6.6, 'x'],
                                            'total': [5.3, 'x']},
                            'child_marriage': {'married_by_15': [0.2, ''],
                                               'married_by_18': [3.5, '']}},
 'Botswana': {'child_labor': {'female': [7.0, 'x,y'],
                              'male': [10.9, 'x,y'],
                              'total': [9.0, 'x,y']},
              'child_marriage': {'married_by_15': ['–', ''],
                                 'married_by_18': ['–', '']}},
 'Brazil': {'child_labor': {'female': [5.7, 'y'],
                            'male': [10.4, 'y'],
                            'total': [8.1, 'y']},
            'child_marriage': {'married_by_15': [10.5, 'x'],
                               'married_by_18': [35.6, 'x']}},
 'Brunei Darussalam': {'child_labor': {'female': ['–', '  '],
                                       'male': ['–', ' '],
                                       'total': ['–', ' ']},
                       'child_marriage': {'married_by_15': ['–', ''],
                                          'married_by_18': ['–', '']}},
 'Bulgaria': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', ' '],
                              'total': ['–', ' ']},
              'child_marriage': {'married_by_15': ['–', ''],
                                 'married_by_18': ['–', '']}},
 'Burkina Faso': {'child_labor': {'female': [36.0, ''],
                                  'male': [42.3, ''],
                                  'total': [39.2, '']},
                  'child_marriage': {'married_by_15': [10.2, ''],
                                     'married_by_18': [51.6, '']}},
 'Burundi': {'child_labor': {'female': [27.1, '  '],
                             'male': [25.5, '  '],
                             'total': [26.3, '  ']},
             'child_marriage': {'married_by_15': [2.5, ''],
                                'married_by_18': [20.4, '']}},
 'Cabo Verde': {'child_labor': {'female': ['–', ''],
                                'male': ['–', ''],
                                'total': [6.4, 'y']},
                'child_marriage': {'married_by_15': [2.8, 'x'],
                                   'married_by_18': [18.0, 'x']}},
 'Cambodia': {'child_labor': {'female': [18.8, 'y'],
                              'male': [19.8, 'y'],
                              'total': [19.3, 'y']},
              'child_marriage': {'married_by_15': [1.9, ''],
                                 'married_by_18': [18.5, '']}},
 'Cameroon': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', '  '],
                              'total': [47.0, 'y']},
              'child_marriage': {'married_by_15': [13.4, ''],
                                 'married_by_18': [38.4, '']}},
 'Canada': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Central African Republic ': {'child_labor': {'female': [29.9, '  '],
                                               'male': [27.2, '  '],
                                               'total': [28.5, '  ']},
                               'child_marriage': {'married_by_15': [29.1, ''],
                                                  'married_by_18': [67.9, '']}},
 'Chad': {'child_labor': {'female': [27.8, '  '],
                          'male': [24.5, '  '],
                          'total': [26.1, '  ']},
          'child_marriage': {'married_by_15': [29.0, ''],
                             'married_by_18': [68.1, '']}},
 'Chile': {'child_labor': {'female': ['–', ''],
                           'male': ['–', ''],
                           'total': [6.6, 'y']},
           'child_marriage': {'married_by_15': ['–', ''],
                              'married_by_18': ['–', '']}},
 'China': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': ['–', ''],
                              'married_by_18': ['–', '']}},
 'Colombia': {'child_labor': {'female': [6.6, 'y'],
                              'male': [12.5, 'y'],
                              'total': [9.7, 'y']},
              'child_marriage': {'married_by_15': [5.6, ''],
                                 'married_by_18': [23.0, '']}},
 'Comoros': {'child_labor': {'female': [23.8, ''],
                             'male': [20.2, ''],
                             'total': [22.0, '']},
             'child_marriage': {'married_by_15': [10.0, ''],
                                'married_by_18': [31.6, '']}},
 'Congo': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', '  '],
                           'total': [23.3, 'y']},
           'child_marriage': {'married_by_15': [6.1, ''],
                              'married_by_18': [32.6, '']}},
 'Cook Islands': {'child_labor': {'female': ['–', '  '],
                                  'male': ['–', ' '],
                                  'total': ['–', ' ']},
                  'child_marriage': {'married_by_15': ['–', ''],
                                     'married_by_18': ['–', '']}},
 'Costa Rica': {'child_labor': {'female': [4.6, ''],
                                'male': [3.5, ''],
                                'total': [4.1, '']},
                'child_marriage': {'married_by_15': [6.8, ''],
                                   'married_by_18': [21.2, '']}},
 'Croatia': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Cuba': {'child_labor': {'female': ['–', '  '],
                          'male': ['–', ' '],
                          'total': ['–', ' ']},
          'child_marriage': {'married_by_15': [4.7, ''],
                             'married_by_18': [26.0, '']}},

 'Cyprus': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Czech Republic': {'child_labor': {'female': ['–', '  '],
                                    'male': ['–', ' '],
                                    'total': ['–', ' ']},
                    'child_marriage': {'married_by_15': ['–', ''],
                                       'married_by_18': ['–', '']}},
 "Côte d'Ivoire": {'child_labor': {'female': [27.5, '  '],
                                   'male': [25.4, '  '],
                                   'total': [26.4, '  ']},
                   'child_marriage': {'married_by_15': [9.8, ''],
                                      'married_by_18': [33.2, '']}},
 "Democratic People's Republic of Korea": {'child_labor': {'female': ['–',
                                                                      '  '],
                                                           'male': ['–', ' '],
                                                           'total': ['–', ' ']},
                                           'child_marriage': {'married_by_15': ['–',
                                                                                ''],
                                                              'married_by_18': ['–',
                                                                                '']}},
 'Democratic Republic of the Congo': {'child_labor': {'female': [40.7, 'y'],
                                                      'male': [36.1, 'y'],
                                                      'total': [38.4, 'y']},
                                      'child_marriage': {'married_by_15': [10.0,
                                                                           ''],
                                                         'married_by_18': [37.3,
                                                                           '']}},
 'Denmark': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Djibouti': {'child_labor': {'female': [7.7, 'x'],
                              'male': [7.6, 'x'],
                              'total': [7.7, 'x']},
              'child_marriage': {'married_by_15': [1.8, 'x'],
                                 'married_by_18': [5.4, 'x']}},
 'Dominica': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', ' '],
                              'total': ['–', ' ']},
              'child_marriage': {'married_by_15': ['–', ''],
                                 'married_by_18': ['–', '']}},
 'Dominican Republic': {'child_labor': {'female': ['–', '  '],
                                        'male': ['–', '  '],
                                        'total': [12.8, 'y']},
                        'child_marriage': {'married_by_15': [10.2, ''],
                                           'married_by_18': [36.5, '']}},
 'Ecuador': {'child_labor': {'female': [2.4, 'y'],
                             'male': [3.5, 'y'],
                             'total': [3.0, 'y']},
             'child_marriage': {'married_by_15': [3.8, 'x'],
                                'married_by_18': [22.2, 'x']}},
 'Egypt': {'child_labor': {'female': [5.8, 'y'],
                           'male': [8.1, 'y'],
                           'total': [7.0, 'y']},
           'child_marriage': {'married_by_15': [2.0, ''],
                              'married_by_18': [17.4, '']}},
 'El Salvador': {'child_labor': {'female': ['–', ''],
                                 'male': ['–', ''],
                                 'total': [19.0, 'y']},
                 'child_marriage': {'married_by_15': [5.0, ''],
                                    'married_by_18': [25.4, '']}},
 'Equatorial Guinea': {'child_labor': {'female': [27.6, 'x'],
                                       'male': [27.9, 'x'],
                                       'total': [27.8, 'x']},
                       'child_marriage': {'married_by_15': [8.6, ''],
                                          'married_by_18': [29.5, '']}},
 'Eritrea': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': [12.9, ''],
                                'married_by_18': [40.7, '']}},
 'Estonia': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Ethiopia': {'child_labor': {'female': [23.5, ''],
                              'male': [31.1, ''],
                              'total': [27.4, '']},
              'child_marriage': {'married_by_15': [16.3, ''],
                                 'married_by_18': [41.0, '']}},
 'Fiji': {'child_labor': {'female': ['–', '  '],
                          'male': ['–', ' '],
                          'total': ['–', ' ']},
          'child_marriage': {'married_by_15': ['–', ''],
                             'married_by_18': ['–', '']}},
 'Finland': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'France': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Gabon': {'child_labor': {'female': [11.6, '  '],
                           'male': [15.4, ' '],
                           'total': [13.4, ' ']},
           'child_marriage': {'married_by_15': [5.6, ''],
                              'married_by_18': [21.9, '']}},
 'Gambia': {'child_labor': {'female': [17.5, '  '],
                            'male': [20.9, '  '],
                            'total': [19.2, '  ']},
            'child_marriage': {'married_by_15': [9.3, ''],
                               'married_by_18': [30.4, '']}},
 'Georgia': {'child_labor': {'female': [16.6, 'x'],
                             'male': [20.0, 'x'],
                             'total': [18.4, 'x']},
             'child_marriage': {'married_by_15': [1.1, ''],
                                'married_by_18': [14.0, '']}},
 'Germany': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Ghana': {'child_labor': {'female': [20.8, 'y'],
                           'male': [22.7, 'y'],
                           'total': [21.8, 'y']},
           'child_marriage': {'married_by_15': [4.9, ''],
                              'married_by_18': [20.7, '']}},
 'Greece': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Grenada': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Guatemala': {'child_labor': {'female': [16.1, 'y'],
                               'male': [35.1, 'y'],
                               'total': [25.8, 'y']},
               'child_marriage': {'married_by_15': [7.1, ''],
                                  'married_by_18': [30.3, '']}},
 'Guinea': {'child_labor': {'female': [27.4, ''],
                            'male': [29.2, ''],
                            'total': [28.3, '']},
            'child_marriage': {'married_by_15': [21.3, ''],
                               'married_by_18': [51.7, '']}},
 'Guinea-Bissau': {'child_labor': {'female': [36.4, '  '],
                                   'male': [39.5, '  '],
                                   'total': [38.0, '  ']},
                   'child_marriage': {'married_by_15': [6.5, ''],
                                      'married_by_18': [22.0, '']}},
 'Guyana': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', '  '],
                            'total': [18.3, 'y']},
            'child_marriage': {'married_by_15': [5.5, ''],
                               'married_by_18': [23.0, '']}},
 'Haiti': {'child_labor': {'female': [24.3, '  '],
                           'male': [24.5, '  '],
                           'total': [24.4, '  ']},
           'child_marriage': {'married_by_15': [2.8, ''],
                              'married_by_18': [17.5, '']}},
 'Holy See': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', ' '],
                              'total': ['–', ' ']},
              'child_marriage': {'married_by_15': ['–', ''],
                                 'married_by_18': ['–', '']}},
 'Honduras': {'child_labor': {'female': [8.0, 'y'],
                              'male': [22.4, 'y'],
                              'total': [15.3, 'y']},
              'child_marriage': {'married_by_15': [7.6, ''],
                                 'married_by_18': [33.6, '']}},
 'Hungary': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Iceland': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'India': {'child_labor': {'female': [11.9, 'x'],
                           'male': [11.6, 'x'],
                           'total': [11.8, 'x']},
           'child_marriage': {'married_by_15': [18.2, 'x'],
                              'married_by_18': [47.4, 'x']}},
 'Indonesia': {'child_labor': {'female': [5.8, ''],
                               'male': [7.9, ''],
                               'total': [6.9, '']},
               'child_marriage': {'married_by_15': ['–', ''],
                                  'married_by_18': [13.6, '']}},
 'Iran (Islamic Republic of)': {'child_labor': {'female': [10.2, 'y'],
                                                'male': [12.5, 'y'],
                                                'total': [11.4, 'y']},
                                'child_marriage': {'married_by_15': [2.7, ''],
                                                   'married_by_18': [16.7,
                                                                     '']}},
 'Iraq': {'child_labor': {'female': [4.0, '  '],
                          'male': [5.4, '  '],
                          'total': [4.7, '  ']},
          'child_marriage': {'married_by_15': [4.6, ''],
                             'married_by_18': [24.3, '']}},
 'Ireland': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Israel': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Italy': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': ['–', ''],
                              'married_by_18': ['–', '']}},
 'Jamaica': {'child_labor': {'female': [3.2, '  '],
                             'male': [3.5, '  '],
                             'total': [3.3, '  ']},
             'child_marriage': {'married_by_15': [1.4, ''],
                                'married_by_18': [7.9, '']}},
 'Japan': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': ['–', ''],
                              'married_by_18': ['–', '']}},
 'Jordan': {'child_labor': {'female': [0.4, 'x,y'],
                            'male': [3.2, 'x,y'],
                            'total': [1.6, 'x,y']},
            'child_marriage': {'married_by_15': [0.3, ''],
                               'married_by_18': [8.4, '']}},
 'Kazakhstan': {'child_labor': {'female': [2.1, 'x'],
                                'male': [2.4, 'x'],
                                'total': [2.2, 'x']},
                'child_marriage': {'married_by_15': [0.3, ''],
                                   'married_by_18': [6.1, '']}},
 'Kenya': {'child_labor': {'female': [25.2, 'x'],
                           'male': [26.5, 'x'],
                           'total': [25.9, 'x']},
           'child_marriage': {'married_by_15': [4.4, ''],
                              'married_by_18': [22.9, '']}},
 'Kiribati': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', ' '],
                              'total': ['–', ' ']},
              'child_marriage': {'married_by_15': [2.8, ''],
                                 'married_by_18': [20.3, '']}},
 'Kuwait': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Kyrgyzstan': {'child_labor': {'female': [21.5, 'y'],
                                'male': [29.9, 'y'],
                                'total': [25.8, 'y']},
                'child_marriage': {'married_by_15': [0.9, ''],
                                   'married_by_18': [11.6, '']}},
 "Lao People's Democratic Republic": {'child_labor': {'female': [11.2, 'y'],
                                                      'male': [9.0, 'y'],
                                                      'total': [10.1, 'y']},
                                      'child_marriage': {'married_by_15': [8.9,
                                                                           ''],
                                                         'married_by_18': [35.4,
                                                                           '']}},
 'Latvia': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Lebanon': {'child_labor': {'female': [0.9, ''],
                             'male': [2.7, ''],
                             'total': [1.9, '']},
             'child_marriage': {'married_by_15': [1.2, ''],
                                'married_by_18': [6.1, '']}},
 'Lesotho': {'child_labor': {'female': [20.7, 'x'],
                             'male': [25.0, 'x'],
                             'total': [22.9, 'x']},
             'child_marriage': {'married_by_15': [2.3, ''],
                                'married_by_18': [18.8, '']}},
 'Liberia': {'child_labor': {'female': [20.5, 'x'],
                             'male': [21.1, 'x'],
                             'total': [20.8, 'x']},
             'child_marriage': {'married_by_15': [8.8, ''],
                                'married_by_18': [35.9, '']}},
 'Libya': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': ['–', ''],
                              'married_by_18': ['–', '']}},
 'Liechtenstein': {'child_labor': {'female': ['–', '  '],
                                   'male': ['–', ' '],
                                   'total': ['–', ' ']},
                   'child_marriage': {'married_by_15': ['–', ''],
                                      'married_by_18': ['–', '']}},
 'Lithuania': {'child_labor': {'female': ['–', '  '],
                               'male': ['–', ' '],
                               'total': ['–', ' ']},
               'child_marriage': {'married_by_15': ['–', ''],
                                  'married_by_18': ['–', '']}},
 'Luxembourg': {'child_labor': {'female': ['–', '  '],
                                'male': ['–', ' '],
                                'total': ['–', ' ']},
                'child_marriage': {'married_by_15': ['–', ''],
                                   'married_by_18': ['–', '']}},
 'Madagascar': {'child_labor': {'female': [22.6, 'y'],
                                'male': [23.2, 'y'],

                                'total': [22.9, 'y']},
                'child_marriage': {'married_by_15': [12.4, ''],
                                   'married_by_18': [41.2, '']}},
 'Malawi': {'child_labor': {'female': [36.8, 'y'],
                            'male': [41.7, 'y'],
                            'total': [39.3, 'y']},
            'child_marriage': {'married_by_15': [8.9, ''],
                               'married_by_18': [46.3, '']}},
 'Malaysia': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', ' '],
                              'total': ['–', ' ']},
              'child_marriage': {'married_by_15': ['–', ''],
                                 'married_by_18': ['–', '']}},
 'Maldives': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', ' '],
                              'total': ['–', ' ']},
              'child_marriage': {'married_by_15': [0.3, ''],
                                 'married_by_18': [3.9, '']}},
 'Mali': {'child_labor': {'female': [20.7, '  '],
                          'male': [22.0, '  '],
                          'total': [21.4, '  ']},
          'child_marriage': {'married_by_15': [14.5, ''],
                             'married_by_18': [55.0, '']}},
 'Malta': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': ['–', ''],
                              'married_by_18': ['–', '']}},
 'Marshall Islands': {'child_labor': {'female': ['–', '  '],
                                      'male': ['–', ' '],
                                      'total': ['–', ' ']},
                      'child_marriage': {'married_by_15': [5.6, 'x'],
                                         'married_by_18': [26.3, 'x']}},
 'Mauritania': {'child_labor': {'female': [14.9, ''],
                                'male': [14.3, ''],
                                'total': [14.6, '']},
                'child_marriage': {'married_by_15': [14.2, ''],
                                   'married_by_18': [34.3, '']}},
 'Mauritius': {'child_labor': {'female': ['–', '  '],
                               'male': ['–', ' '],
                               'total': ['–', ' ']},
               'child_marriage': {'married_by_15': ['–', ''],
                                  'married_by_18': ['–', '']}},
 'Mexico': {'child_labor': {'female': ['–', ''],
                            'male': ['–', ''],
                            'total': [4.2, '']},
            'child_marriage': {'married_by_15': [5.1, ''],
                               'married_by_18': [22.9, '']}},
 'Micronesia (Federated States of)': {'child_labor': {'female': ['–', '  '],
                                                      'male': ['–', ' '],
                                                      'total': ['–', ' ']},
                                      'child_marriage': {'married_by_15': ['–',
                                                                           ''],
                                                         'married_by_18': ['–',
                                                                           '']}},
 'Monaco': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Mongolia': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', '  '],
                              'total': [15.2, 'y']},
              'child_marriage': {'married_by_15': [0.1, ''],
                                 'married_by_18': [4.7, '']}},
 'Montenegro': {'child_labor': {'female': [9.8, 'y'],
                                'male': [15.3, 'y'],
                                'total': [12.5, 'y']},
                'child_marriage': {'married_by_15': [0.6, ''],
                                   'married_by_18': [4.5, '']}},
 'Morocco': {'child_labor': {'female': [7.5, 'x'],
                             'male': [9.1, 'x'],
                             'total': [8.3, 'x']},
             'child_marriage': {'married_by_15': [2.5, 'x'],
                                'married_by_18': [15.9, 'x']}},
 'Mozambique': {'child_labor': {'female': [23.8, 'x'],
                                'male': [20.5, 'x'],
                                'total': [22.2, 'x']},
                'child_marriage': {'married_by_15': [14.3, ''],
                                   'married_by_18': [48.2, '']}},
 'Myanmar': {'child_labor': {'female': ['–', '  '],
                             'male': ['–', ' '],
                             'total': ['–', ' ']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Namibia': {'child_labor': {'female': ['–', ''],
                             'male': ['–', ''],
                             'total': ['–', '']},
             'child_marriage': {'married_by_15': [1.6, ''],
                                'married_by_18': [6.9, '']}},
 'Nauru': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': [1.9, 'x'],
                              'married_by_18': [26.8, 'x']}},
 'Nepal': {'child_labor': {'female': [38.3, 'y'],
                           'male': [36.5, 'y'],
                           'total': [37.4, 'y']},
           'child_marriage': {'married_by_15': [10.4, ''],
                              'married_by_18': [36.6, '']}},
 'Netherlands': {'child_labor': {'female': ['–', '  '],
                                 'male': ['–', ' '],
                                 'total': ['–', ' ']},
                 'child_marriage': {'married_by_15': ['–', ''],
                                    'married_by_18': ['–', '']}},
 'New Zealand': {'child_labor': {'female': ['–', '  '],
                                 'male': ['–', ' '],
                                 'total': ['–', ' ']},
                 'child_marriage': {'married_by_15': ['–', ''],
                                    'married_by_18': ['–', '']}},
 'Nicaragua': {'child_labor': {'female': [11.2, 'x'],
                               'male': [17.6, 'x'],
                               'total': [14.9, 'x']},
               'child_marriage': {'married_by_15': [10.4, 'x'],
                                  'married_by_18': [40.6, 'x']}},
 'Niger': {'child_labor': {'female': [30.1, '  '],
                           'male': [30.8, '  '],
                           'total': [30.5, '  ']},
           'child_marriage': {'married_by_15': [28.0, ''],
                              'married_by_18': [76.3, '']}},
 'Nigeria': {'child_labor': {'female': [25.3, '  '],
                             'male': [24.1, ' '],
                             'total': [24.7, '']},
             'child_marriage': {'married_by_15': [17.3, ''],
                                'married_by_18': [42.8, '']}},
 'Niue': {'child_labor': {'female': ['–', '  '],
                          'male': ['–', ' '],
                          'total': ['–', ' ']},
          'child_marriage': {'married_by_15': ['–', ''],
                             'married_by_18': ['–', '']}},
 'Norway': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Oman': {'child_labor': {'female': ['–', '  '],
                          'male': ['–', ' '],
                          'total': ['–', ' ']},
          'child_marriage': {'married_by_15': ['–', ''],
                             'married_by_18': ['–', '']}},
 'Pakistan': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', ' '],
                              'total': ['–', ' ']},
              'child_marriage': {'married_by_15': [2.8, ''],
                                 'married_by_18': [21.0, '']}},
 'Palau': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': ['–', ''],
                              'married_by_18': ['–', '']}},
 'Panama': {'child_labor': {'female': [3.0, 'y'],
                            'male': [8.0, 'y'],
                            'total': [5.6, 'y']},
            'child_marriage': {'married_by_15': [6.8, ''],
                               'married_by_18': [26.4, '']}},
 'Papua New Guinea': {'child_labor': {'female': ['–', '  '],
                                      'male': ['–', ' '],
                                      'total': ['–', ' ']},
                      'child_marriage': {'married_by_15': [2.1, 'x'],
                                         'married_by_18': [21.3, 'x']}},
 'Paraguay': {'child_labor': {'female': [23.5, 'y'],
                              'male': [31.8, 'y'],
                              'total': [27.6, 'y']},
              'child_marriage': {'married_by_15': ['–', ''],
                                 'married_by_18': [17.9, 'x']}},
 'Peru': {'child_labor': {'female': [36.3, 'x,y'],
                          'male': [30.6, 'x,y'],
                          'total': [33.5, 'x,y']},
          'child_marriage': {'married_by_15': [2.6, ''],
                             'married_by_18': [18.6, '']}},
 'Philippines': {'child_labor': {'female': [7.9, 'y'],
                                 'male': [14.1, 'y'],
                                 'total': [11.1, 'y']},
                 'child_marriage': {'married_by_15': [2.0, ''],
                                    'married_by_18': [15.0, '']}},
 'Poland': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Portugal': {'child_labor': {'female': [2.5, 'x,y'],
                              'male': [4.2, 'x,y'],
                              'total': [3.4, 'x,y']},
              'child_marriage': {'married_by_15': ['–', ''],
                                 'married_by_18': ['–', '']}},
 'Qatar': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': [0.0, ''],
                              'married_by_18': [4.2, '']}},
 'Republic of Korea': {'child_labor': {'female': ['–', '  '],
                                       'male': ['–', ' '],
                                       'total': ['–', ' ']},
                       'child_marriage': {'married_by_15': ['–', ''],
                                          'married_by_18': ['–', '']}},
 'Republic of Moldova': {'child_labor': {'female': [12.3, ''],
                                         'male': [20.2, ''],
                                         'total': [16.3, '']},
                         'child_marriage': {'married_by_15': [0.4, ''],
                                            'married_by_18': [12.2, '']}},
 'Romania': {'child_labor': {'female': [0.7, 'x'],
                             'male': [1.2, 'x'],
                             'total': [0.9, 'x']},
             'child_marriage': {'married_by_15': ['–', ''],
                                'married_by_18': ['–', '']}},
 'Russian Federation': {'child_labor': {'female': ['–', '  '],
                                        'male': ['–', ' '],
                                        'total': ['–', ' ']},
                        'child_marriage': {'married_by_15': ['–', ''],
                                           'married_by_18': ['–', '']}},
 'Rwanda': {'child_labor': {'female': [30.4, '  '],
                            'male': [26.7, '  '],
                            'total': [28.5, '  ']},
            'child_marriage': {'married_by_15': [0.8, ''],
                               'married_by_18': [8.1, '']}},
 'Saint Kitts and Nevis': {'child_labor': {'female': ['–', '  '],
                                           'male': ['–', ' '],
                                           'total': ['–', ' ']},
                           'child_marriage': {'married_by_15': ['–', ''],
                                              'married_by_18': ['–', '']}},
 'Saint Lucia': {'child_labor': {'female': [2.9, '  '],
                                 'male': [4.9, ' '],
                                 'total': [3.9, ' ']},
                 'child_marriage': {'married_by_15': [1.3, ''],
                                    'married_by_18': [7.5, '']}},
 'Saint Vincent and the Grenadines': {'child_labor': {'female': ['–', '  '],
                                                      'male': ['–', ' '],
                                                      'total': ['–', ' ']},
                                      'child_marriage': {'married_by_15': ['–',
                                                                           ''],
                                                         'married_by_18': ['–',
                                                                           '']}},
 'Samoa': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': [0.7, ''],
                              'married_by_18': [10.8, '']}},
 'San Marino': {'child_labor': {'female': ['–', '  '],
                                'male': ['–', ' '],
                                'total': ['–', ' ']},
                'child_marriage': {'married_by_15': ['–', ''],
                                   'married_by_18': ['–', '']}},
 'Sao Tome and Principe': {'child_labor': {'female': ['–', '  '],
                                           'male': ['–', '  '],
                                           'total': [26.0, 'y']},
                           'child_marriage': {'married_by_15': [5.0, ''],
                                              'married_by_18': [34.4, '']}},
 'Saudi Arabia': {'child_labor': {'female': ['–', '  '],
                                  'male': ['–', ' '],
                                  'total': ['–', ' ']},
                  'child_marriage': {'married_by_15': ['–', ''],
                                     'married_by_18': ['–', '']}},
 'Senegal': {'child_labor': {'female': [10.0, ''],
                             'male': [19.0, ''],
                             'total': [14.5, '']},
             'child_marriage': {'married_by_15': [8.7, ''],
                                'married_by_18': [32.3, '']}},
 'Serbia': {'child_labor': {'female': [6.6, 'y'],
                            'male': [12.2, 'y'],
                            'total': [9.5, 'y']},
            'child_marriage': {'married_by_15': [0.3, ''],
                               'married_by_18': [3.2, '']}},
 'Seychelles': {'child_labor': {'female': ['–', '  '],
                                'male': ['–', ' '],
                                'total': ['–', ' ']},
                'child_marriage': {'married_by_15': ['–', ''],
                                   'married_by_18': ['–', '']}},
 'Sierra Leone': {'child_labor': {'female': [36.5, '  '],
                                  'male': [38.2, '  '],
                                  'total': [37.4, '  ']},
                  'child_marriage': {'married_by_15': [12.5, ''],
                                     'married_by_18': [38.9, '']}},
 'Singapore': {'child_labor': {'female': ['–', '  '],
                               'male': ['–', ' '],
                               'total': ['–', ' ']},
               'child_marriage': {'married_by_15': ['–', ''],
                                  'married_by_18': ['–', '']}},
 'Slovakia': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', ' '],
                              'total': ['–', ' ']},
              'child_marriage': {'married_by_15': ['–', ''],
                                 'married_by_18': ['–', '']}},
 'Slovenia': {'child_labor': {'female': ['–', '  '],
                              'male': ['–', ' '],
                              'total': ['–', ' ']},
              'child_marriage': {'married_by_15': ['–', ''],
                                 'married_by_18': ['–', '']}},
 'Solomon Islands': {'child_labor': {'female': ['–', '  '],
                                     'male': ['–', ' '],
                                     'total': ['–', ' ']},
                     'child_marriage': {'married_by_15': [3.1, 'x'],
                                        'married_by_18': [22.4, 'x']}},
 'Somalia': {'child_labor': {'female': [53.6, 'x'],
                             'male': [44.5, 'x'],
                             'total': [49.0, 'x']},
             'child_marriage': {'married_by_15': [8.4, 'x'],
                                'married_by_18': [45.3, 'x']}},
 'South Africa': {'child_labor': {'female': ['–', '  '],
                                  'male': ['–', ' '],
                                  'total': ['–', ' ']},
                  'child_marriage': {'married_by_15': [0.8, 'x'],
                                     'married_by_18': [5.6, 'x']}},
 'South Sudan': {'child_labor': {'female': ['–', ''],
                                 'male': ['–', ''],
                                 'total': ['–', '']},
                 'child_marriage': {'married_by_15': [8.9, ''],
                                    'married_by_18': [51.5, '']}},
 'Spain': {'child_labor': {'female': ['–', '  '],
                           'male': ['–', ' '],
                           'total': ['–', ' ']},
           'child_marriage': {'married_by_15': ['–', ''],
                              'married_by_18': ['–', '']}},
 'Sri Lanka': {'child_labor': {'female': [1.6, 'y'],
                               'male': [3.3, 'y'],
                               'total': [2.5, 'y']},
               'child_marriage': {'married_by_15': [1.7, 'x'],
                                  'married_by_18': [11.8, 'x']}},
 'State of Palestine': {'child_labor': {'female': [4.0, '  '],
                                        'male': [7.4, ' '],
                                        'total': [5.7, ' ']},
                        'child_marriage': {'married_by_15': [1.0, ''],
                                           'married_by_18': [15.3, '']}},
 'Sudan': {'child_labor': {'female': ['–', ''],
                           'male': ['–', ''],
                           'total': [24.9, 'y']},
           'child_marriage': {'married_by_15': [7.2, ''],
                              'married_by_18': [32.9, '']}},
 'Suriname': {'child_labor': {'female': [4.1, '  '],
                              'male': [4.1, '  '],
                              'total': [4.1, '  ']},
              'child_marriage': {'married_by_15': [5.2, ''],
                                 'married_by_18': [18.8, '']}},
 'Swaziland': {'child_labor': {'female': [6.9, '  '],
                               'male': [7.7, '  '],
                               'total': [7.3, '  ']},
               'child_marriage': {'married_by_15': [0.7, ''],
                                  'married_by_18': [6.5, '']}},
 'Sweden': {'child_labor': {'female': ['–', '  '],
                            'male': ['–', ' '],
                            'total': ['–', ' ']},
            'child_marriage': {'married_by_15': ['–', ''],
                               'married_by_18': ['–', '']}},
 'Switzerland': {'child_labor': {'female': ['–', '  '],
                                 'male': ['–', ' '],
                                 'total': ['–', ' ']},

            'child_marriage': {'married_by_15': [0.0, 'x'],
                               'married_by_18': [9.9, 'x']}},
 'Uganda': {'child_labor': {'female': [15.6, 'y'],
                            'male': [16.9, 'y'],
                            'total': [16.3, 'y']},
            'child_marriage': {'married_by_15': [9.9, ''],
                               'married_by_18': [39.7, '']}},
 'Ukraine': {'child_labor': {'female': [2.4, '  '],
                             'male': [2.5, '  '],
                             'total': [2.4, '  ']},
             'child_marriage': {'married_by_15': [0.1, ''],
                                'married_by_18': [9.1, '']}},
 'United Arab Emirates': {'child_labor': {'female': ['–', '  '],
                                          'male': ['–', ' '],
                                          'total': ['–', ' ']},
                          'child_marriage': {'married_by_15': ['–', ''],
                                             'married_by_18': ['–', '']}},
 'United Kingdom': {'child_labor': {'female': ['–', '  '],
                                    'male': ['–', ' '],
                                    'total': ['–', ' ']},
                    'child_marriage': {'married_by_15': ['–', ''],
                                       'married_by_18': ['–', '']}},
 'United Republic of Tanzania': {'child_labor': {'female': [28.3, 'y'],
                                                 'male': [29.3, 'y'],
                                                 'total': [28.8, 'y']},
                                 'child_marriage': {'married_by_15': [6.6, ''],
                                                    'married_by_18': [36.9,
                                                                      '']}},
 'United States': {'child_labor': {'female': ['–', '  '],
                                   'male': ['–', ' '],
                                   'total': ['–', ' ']},
                   'child_marriage': {'married_by_15': ['–', ''],
                                      'married_by_18': ['–', '']}},
 'Uruguay': {'child_labor': {'female': [7.5, 'x,y'],
                             'male': [8.3, 'x,y'],
                             'total': [7.9, 'x,y']},
             'child_marriage': {'married_by_15': [0.7, ''],
                                'married_by_18': [24.6, '']}},
 'Uzbekistan': {'child_labor': {'female': ['–', '  '],
                                'male': ['–', ' '],
                                'total': ['–', ' ']},
                'child_marriage': {'married_by_15': [0.3, 'x'],
                                   'married_by_18': [7.2, 'x']}},
 'Vanuatu': {'child_labor': {'female': [15.7, 'y'],
                             'male': [14.8, 'y'],
                             'total': [15.2, 'y']},
             'child_marriage': {'married_by_15': [2.5, ''],
                                'married_by_18': [21.4, '']}},
 'Venezuela (Bolivarian Republic of)': {'child_labor': {'female': [6.2, 'x'],
                                                        'male': [9.2, 'x'],
                                                        'total': [7.7, 'x']},
                                        'child_marriage': {'married_by_15': ['–',
                                                                             ''],
                                                           'married_by_18': ['–',
                                                                             '']}},
 'Viet Nam': {'child_labor': {'female': [16.2, 'y'],
                              'male': [16.6, 'y'],
                              'total': [16.4, 'y']},
              'child_marriage': {'married_by_15': [0.9, ''],
                                 'married_by_18': [10.6, '']}},
 'Yemen': {'child_labor': {'female': [24.4, 'x'],
                           'male': [21.1, 'x'],
                           'total': [22.7, 'x']},
           'child_marriage': {'married_by_15': [9.4, ''],
                              'married_by_18': [31.9, '']}},
 'Zambia': {'child_labor': {'female': [39.5, 'x,y'],
                            'male': [41.6, 'x,y'],
                            'total': [40.6, 'x,y']},
            'child_marriage': {'married_by_15': [5.9, ''],
                               'married_by_18': [31.4, '']}},
 'Zimbabwe': {'child_labor': {'female': ['–', ''],
                              'male': ['–', ''],
                              'total': ['–', '']},
              'child_marriage': {'married_by_15': [4.0, ''],
                                 'married_by_18': [33.5, '']}}}